SELECT DISTINCT
	ACC.ACCIDENT_NO,
	EXTRACT( YEAR FROM ACC.ACCIDENTDATE ) AS YEAR,
	MONTHNAME( ACC.ACCIDENTDATE ) AS MONTH,
CASE
	  WHEN EXTRACT( HOUR FROM ( CONCAT( ACC.ACCIDENTDATE, " ", ACC.ACCIDENTTIME ) ) ) >= 06 
			AND EXTRACT( HOUR FROM ( CONCAT( ACC.ACCIDENTDATE, " ", ACC.ACCIDENTTIME ) ) ) < 12 THEN 'Morning'
		WHEN EXTRACT( HOUR FROM ( CONCAT( ACC.ACCIDENTDATE, " ", ACC.ACCIDENTTIME ) ) ) >= 12 
			AND EXTRACT( HOUR FROM ( CONCAT( ACC.ACCIDENTDATE, " ", ACC.ACCIDENTTIME ) ) ) < 18 THEN 'Afternoon' 
		WHEN EXTRACT( HOUR FROM ( CONCAT( ACC.ACCIDENTDATE, " ", ACC.ACCIDENTTIME ) ) ) >= 18 
			AND EXTRACT( HOUR FROM ( CONCAT( ACC.ACCIDENTDATE, " ", ACC.ACCIDENTTIME ) ) ) < 24 THEN 'Evening' 
		ELSE 'Night' 
					END AS "Time Zone",
		ACC.`DAY WEEK DESCRIPTION` AS "Week Day",
		ACC.`LIGHT CONDITION DESC` AS "Light Condition",
		ACC.`Road Geometry Desc` AS "Road Geometry",
		ACC.SPEED_ZONE AS "Speed Zone",
			CASE
			WHEN N.`DEG URBAN NAME` LIKE '%MEL%' THEN
					"Melbourne Region" ELSE 'Victoria Region' 
			END AS 'Region',
			N.`REGION NAME` AS "Sub Region",
			P.AGE,
			P.SEATING_POSITION AS "Seating Position",
			P.HELMET_BELT_WORN AS "Helmet or Belt",
			V.`VEHICLE TYPE DESC` AS "Vehicle Type",
			V.`TRAFFIC CONTROL DESC` AS "Traffic Control",
			P.`ROAD USER TYPE DESC` AS "Road User",
			R.`Surface Cond Desc` AS "Road Surface Condition",
			A.`Atmosph Cond Desc` AS "Atmospheric Condition",
			ACC.SEVERITY 
			FROM
				ACCIDENT ACC
				LEFT OUTER JOIN NODE N ON ACC.ACCIDENT_NO = N.ACCIDENT_NO 
				AND ACC.NODE_ID = N.NODE_ID
				LEFT OUTER JOIN PERSON P ON ACC.ACCIDENT_NO = P.ACCIDENT_NO
				LEFT OUTER JOIN VEHICLE V ON V.ACCIDENT_NO = P.ACCIDENT_NO 
				AND P.VEHICLE_ID = V.VEHICLE_ID
				LEFT OUTER JOIN ROAD_SURFACE_COND R ON R.ACCIDENT_NO = ACC.ACCIDENT_NO
				LEFT OUTER JOIN ATMOSPHERIC_COND A ON A.ACCIDENT_NO = ACC.ACCIDENT_NO 
			WHERE
				P.AGE IS NOT NULL 
				AND P.AGE <= 16 
				AND 			ACC.SEVERITY IS NOT null
				AND EXTRACT( YEAR FROM ACC.ACCIDENTDATE ) = 2017
		ORDER BY
	ACC.ACCIDENT_NO DESC;